<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<test-results name="C:\Clean-Delphi-API\api_test\exe\api_test.exe" total="9" errors="0" failures="1" ignored="0" inconclusive="0" not-run="0" skipped="0" invalid="0" date="2021-03-11" time="0.097">
  <culture-info current-culture="en" current-uiculture="en" />
  <test-suite type="Assembly" name="api_test.exe" executed="true" result="Failure" success="False" time="0.097" asserts="0">
    <results>
        <test-suite type="Namespace" name="signup_test" executed="true" result="Failure" success="False" time="0.096" asserts="0" >
          <results>
              <test-suite type="Fixture" name="TSignupTest" executed="True" result="Failure" success="False" time="0.096" >
                <results>
                  <test-case name="MissingParamName" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                  <test-case name="MissingParamEmail" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                  <test-case name="MissingParamPassword" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                  <test-case name="MissingParamPasswordConfirmation" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                  <test-case name="PasswordConfirmationFails" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                  <test-case name="InvalidParamErrorEmail" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                  <test-case name="ShouldAllEmailValidatorWithCorrectEmail" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                  <test-case name="ShouldReturnError500IfEmailValidatorThrows" executed="True" result="Failure" success="False" time="0.093" asserts="0" >
                    <failure>
                      <message>
                        <![CDATA[ Condition is False when True expected. [Deve retornar {"error":"Internal Server Error"}] ]]>
                      </message>
                      <stack-trace>
                        <![CDATA[  ]]>
                      </stack-trace>
                    </failure>
                  </test-case>
                  <test-case name="ShouldCallAddAccountWithCorrectValues" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                </results>
              </test-suite>
          </results>
        </test-suite>
    </results>
  </test-suite>
</test-results>
